name: flutter_gen_ai_chat_ui
description: A Flutter package for creating AI chat interfaces with streaming responses, markdown support, and extensive customization.
version: 2.0.1
homepage: https://github.com/hooshyar/flutter_gen_ai_chat_ui
repository: https://github.com/hooshyar/flutter_gen_ai_chat_ui
issue_tracker: https://github.com/hooshyar/flutter_gen_ai_chat_ui/issues
documentation: https://github.com/hooshyar/flutter_gen_ai_chat_ui/blob/main/README.md

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.6+2
  intl: ^0.20.2
  flutter_animate: ^4.5.2
  google_fonts: ^6.1.0
  provider: ^6.1.2
  scrollable_positioned_list: ^0.3.8
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  permission_handler: ^11.4.0
  flutter_streaming_text_markdown: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  speech_to_text: ^6.6.1
  network_image_mock: ^2.1.1
  golden_toolkit: ^0.15.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  # Expose integration test files
  assets:
    - integration_test/
    - integration_test/utils/

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
